### ISSUE TITLE
Button in queue not showing up

### ISSUE THREAD

**Issue by orfox32** [Rtxeon/SynthMusic#1]
it seems like the button in queue is not working

**Comment by CodeSuthar** [comment]
Express It Clearly @orfox32

**Comment by CodeSuthar** [comment]
Add Some Images

**Comment by CodeSuthar** [comment]
Oh Do You Mean Button In Queue Command Doesn't Work

**Comment by CodeSuthar** [comment]
As I Checked My Other Users Are Not Having Any Problem

**Comment by orfox32** [comment]
Yeah the button in queue command Yes it is not showing up i don't know why
it has no error in console

**Comment by orfox32** [comment]
It shows the embed in queue but not the buttons

**Comment by CodeSuthar** [comment]
I will update this soon
