### ISSUE TITLE
Type Error Handler/SlashCommands.js

### ISSUE THREAD

**Issue by MarcoSolorzanoZ-65** [Rtxeon/SynthMusic#2]
Having this issue when hosting
![image](https://user-images.githubusercontent.com/32855137/186037071-f7e9c56a-3521-40b2-b020-ef7fd71d2ad0.png)

**Comment by MarcoSolorzanoZ-65** [comment]
Should be reffering to this line 
![image](https://user-images.githubusercontent.com/32855137/186037221-9fc5906c-ed01-4c18-a7ac-1ec4915f2f0f.png)

**Comment by CodeSuthar** [comment]
Sir I Fixed This Issue
